[package]
name = "usrhttpd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "fs"] }
warp = "0.3"
regex = "1"
reqwest = { version = "0.11", features = ["json", "stream", "gzip", "brotli", "deflate", "blocking", "trust-dns"] }
base64 = "0.21"
parking_lot = "0.12"
